apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-application
  template:
    metadata:
      labels:
        app: my-k8s-application
    spec:
      containers:
      - name: my-k8s-application
        image: devopslab2026/my-k8s-application:latest  # your Docker Hub image
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
